module.exports={
    USER_COLLECTION:'user',
    QM_COLLECTION:'Qmanager',
    QUEUE_COLLECTION:'queue_details',
    QUEUESLOT_COLLECTION:'queue_slots',
    HRTIMING_COLLECTION:'hr_timings',
    MINTIMING_COLLECTION:'min_timings',
    BOOKING_COLLECTION:'booking_details'
}